package com.github.alexdochioiu.interfaceinjector;

import com.github.alexdochioiu.timeturner.SurvivorBinding;

import java.util.List;

/**
 * Created by Alex Dochioiu on 30/01/2019
 *
 * TODO this class is now manually generated (as proof of concept). This will be generated by the annotation processor
 */
public class NewPresenter_Binding extends SurvivorBinding.InstanceSaver<NewPresenter> {

    private List<String> survivingElements;

    NewPresenter_Binding(NewPresenter newPresenter) {
        survivingElements = newPresenter.survivingElements;
    }

    @Override
    public void restore(NewPresenter newPresenter) {
        newPresenter.survivingElements = survivingElements;
    }
}
